-- Inventory table for storing stock items used/managed by the garment CRM.

CREATE TABLE IF NOT EXISTS inventory (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_name VARCHAR(255) NOT NULL,
    item_quantity INTEGER NOT NULL,
    item_price DOUBLE PRECISION NOT NULL
);

